### ISSUE TITLE
Add blank lines around Markdown tables to support Pandoc

### ISSUE THREAD

**Issue by matatk** [interagent/prmd#189]
When converting the rendered Markdown to HTML with Pandoc, the tables are not correctly parsed by Pandoc and are output as a paragraph with the table-formatting characters interspersed.

However, if the markdown output by prmd is edited to place a blank line both above and below the tables, Pandoc correctly converts the Markdown table into an HTML table.  Would it be possible for you to add these blank lines in order to support Pandoc?

**Comment by matatk** [comment]
@geemus: thanks for the quick reply; I have had a go at a PR...

**Comment by geemus** [comment]
Just merged, thanks!
