### ISSUE TITLE
reduce necessity for examples

### ISSUE THREAD

**Issue by geemus** [interagent/prmd#199]
Arguably, many of the types are well defined enough that they probably don't need an explicit example (though in some cases it could still be helpful). ie you could default so that all `string` values would have `"example"` as their default (or similar), `number` could have `42`, etc. By providing overridable defaults, you get to a schema that can generate docs faster and only really have to provide examples on things that might be more unusual.

**Comment by tobie** [comment]
Seems like `format` is another good candidate for generated examples (the documentation generator could even keep data available just for this).

**Comment by geemus** [comment]
Yeah, format could definitely work (much better than reversing regexes also). Plenty of room for improvements here for sure.

**Comment by geemus** [comment]
closed by #215
