### ISSUE TITLE
? should prmd render required field information?

### ISSUE THREAD

**Issue by waterlink** [interagent/prmd#204]
You can include or exclude certain field in `required` array. It would be nice to see it in rendered documentation. Currently it doesn't distinguish them in any way.

**Comment by geemus** [comment]
Definitely. Would you be up for making a pull request for this?

**Comment by Sherlock92** [comment]
@geemus I think this has been resolved already ?

**Comment by geemus** [comment]
@Sherlock92 I do believe you are correct, thanks for the reminder!
