### ISSUE TITLE
Empty file created from doc command

### ISSUE THREAD

**Issue by Sherlock92** [interagent/prmd#211]
Given the following schema:

```json
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		},
		"age": {
			"description": "Age in years",
			"type": "integer",
			"minimum": 0
		}
	},
	"required": ["firstName", "lastName"]
}
```

When running `prmd doc simple.json > simple.md`, the file created contains just newlines, and no actual content. In this case I was expecting to see the generated documentation for this schema. 

There are no errors displayed in the console, and this was also the case for me when running the example schemas. Am I doing anything wrong ?

Running on mac OSX Yosemite 10.10.3
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

Many thanks

**Comment by lyczek** [comment]
+1

**Comment by lyczek** [comment]
This is also true for `prmd render`

**Comment by geemus** [comment]
Yeah, so there are some subtle missing things here. We have an expectation that individual schemas can be written for each resource, but that they would then be combined (with the combine command) prior to being run through doc. So if you combine on this single file, it will adjust the format to match expectations and then running the combined version through doc should get you something. Let me know if that doesn't make sense or you have problems. It may well be that we should expand upon documentation to make this clearer (and we certainly welcome any help you might offer in that realm). Thanks!
