### ISSUE TITLE
Document generation fails with simple JSON that verifies

### ISSUE THREAD

**Issue by charlieconcur** [interagent/prmd#213]
The test.json file is...

    {"$schema": "http://json-schema.org/draft-04/schema#","an": {"data": "structure"}}

...and it can be verified...

    prmd verify test.json
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "an": {
        "data": "structure"
      }
    }

...but fails to generate the markdown...

    prmd doc test.json > test.md
    /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/lib/prmd/templates/schema.erb:4:in `result': undefined method `map' for nil:NilClass (NoMethodError)
    	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
    	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
    	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/lib/prmd/core/renderer.rb:49:in `render'
    	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/lib/prmd/commands/render.rb:34:in `render'
    	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/lib/prmd/cli/doc.rb:65:in `execute'
    	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/lib/prmd/cli/base.rb:141:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/lib/prmd/cli.rb:93:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.0/bin/prmd:6:in `<top (required)>'
    	from /usr/bin/prmd:23:in `load'
    	from /usr/bin/prmd:23:in `<main>'

Thanks for any assistance you can give -- totally brand new to all of this...!

**Comment by geemus** [comment]
I think this falls into the same vein as #213, maybe take a peak at that explanation and let me know if you have further questions? Thanks!

**Comment by charlieconcur** [comment]
Hmmmmm....I'm brand new to GIT but I think what you've given me is a circular reference: #213 would seem to be this issue. ;-)

**Comment by geemus** [comment]
Oops! I meant #211 too many tabs open I guess.
