### ISSUE TITLE
Render schemas without any links?

### ISSUE THREAD

**Issue by dominikh** [interagent/prmd#216]
Currently, when a schema has no links, it will not be included in the documentation.

I have some schemata that are only returned as part of other objects. However, I'd still like these schemata to show up on their own, so that they can carry a description.

Is the omission of these schemata on purpose, or a bug? Or am I using JSON schema wrong?

The following patch seems to be all it takes to print those schemata, but before I submitted a PR I wanted to check if the current behaviour is working as intended.

```diff
diff --git i/lib/prmd/templates/schemata.md.erb w/lib/prmd/templates/schemata.md.erb
index df666a4..4ec7b04 100644
--- i/lib/prmd/templates/schemata.md.erb
+++ w/lib/prmd/templates/schemata.md.erb
@@ -1,6 +1,4 @@
 <%-
-  return unless schemata.has_key?('links') && !schemata['links'].empty?
-
   Prmd::Template.render('schemata/helper.erb', options[:template], {
     options:         options,
     resource:        resource,
@@ -26,7 +24,7 @@
 <%- end %>
 
 <%- end %>
-<%- schemata['links'].each do |link, datum| %>
+<%- (schemata['links'] || []).each do |link, datum| %>
 <%=
   Prmd::Template.render('schemata/link.md.erb', options[:template], {
     options:         options,
```

**Comment by geemus** [comment]
It seemed like a reasonable thing to do at the time, but I don't really see any reason why this wouldn't be a positive change. I would welcome the pull request when you get a chance. Thanks!
