### ISSUE TITLE
Link to other schemas from attributes list?

### ISSUE THREAD

**Issue by dominikh** [interagent/prmd#217]
When a schema A references another schema B for one of its properties, schema B will be exploded and each of its attributes will be listed in the attributes table of A. Should we additionally link to the schema, so that the user can explore its description and links? 

Issue #216 relates to this.

**Comment by geemus** [comment]
Sounds good. If we link, I guess you could even argue the exploding is not needed, but the duplication is kind of handy. In any event, the link seems like it would be a welcome addition. Thanks!

**Comment by dominikh** [comment]
I think it's worthwhile to keep the exploded overview. Having to jump around the docs means more context switching, and a lot of the times, just knowing the fields is enough.

I'll work on a PR to add the links.

**Comment by geemus** [comment]
Cool, sounds good, thanks!
