### ISSUE TITLE
Underscores not allowed in resource name/path

### ISSUE THREAD

**Issue by mcclymont** [interagent/prmd#227]
A project I'm working on was upgraded from Rails 3 to Rail 4 recently, and at the same time we upgraded most gems, including prmd due to dependencies.

I already have a schema generated that uses underscores to separate words in resource names, and consequently in the hrefs and my routes.rb, e.g. console_session

57a1800f31b8a0d037706ef25c8c31ca3dfac4bc has broke this for me. *Edit: I don't think it was just this commit. The gem version I used before was 0.6.2, and this commit was tagged back to 0.4.0

Is it possible to modify the regex to include underscores as an allowed character? I think hyphens vs underscores is a convention / style issue that varies across environments.

Commands to show the error:
```bash
~ echo '{
 "description": "temp meta",
 "id": "under-score-test",
 "links": [{
   "href": "https://example.com/api",
   "rel": "self"
 }],
 "title": "Underscore test"
}' > meta.json

~ bundle exec prmd init with-hyphen > with_hyphen.json
~ bundle exec prmd combine --meta meta.json with_hyphen.json | bundle exec prmd verify > /dev/null
( no errors )

~ bundle exec prmd init with_underscore > with_underscore.json
~ bundle exec prmd combine --meta meta.json with_underscore.json | bundle exec prmd verify > /dev/null
#/definitions/with_underscore/links/0/href: failed schema #/definitions/resourceLink/properties/href: /with_underscores does not match /^(\/([a-z][a-z\-]*[a-z]|\{\(.*\)\}))+$/.
#/definitions/with_underscore/links/1/href: failed schema #/definitions/resourceLink/properties/href: /with_underscores/{(%23%2Fdefinitions%2Fwith_underscore%2Fdefinitions%2Fidentity)} does not match /^(\/([a-z][a-z\-]*[a-z]|\{\(.*\)\}))+$/.
#/definitions/with_underscore/links/2/href: failed schema #/definitions/resourceLink/properties/href: /with_underscores/{(%23%2Fdefinitions%2Fwith_underscore%2Fdefinitions%2Fidentity)} does not match /^(\/([a-z][a-z\-]*[a-z]|\{\(.*\)\}))+$/.
#/definitions/with_underscore/links/3/href: failed schema #/definitions/resourceLink/properties/href: /with_underscores does not match /^(\/([a-z][a-z\-]*[a-z]|\{\(.*\)\}))+$/.
#/definitions/with_underscore/links/4/href: failed schema #/definitions/resourceLink/properties/href: /with_underscores/{(%23%2Fdefinitions%2Fwith_underscore%2Fdefinitions%2Fidentity)} does not match /^(\/([a-z][a-z\-]*[a-z]|\{\(.*\)\}))+$/.
```

**Comment by geemus** [comment]
Should be fixed, sorry for the inconvenience and thanks for the detailed report.

**Comment by mcclymont** [comment]
FYI this is not released on Rubygems, likewise #228

**Comment by geemus** [comment]
@mcclymont thanks for the heads up. I have a couple other existing issues I want to look at here, but will try to cut a release later today.

**Comment by geemus** [comment]
Should now be out as part of v0.8.0.
