### ISSUE TITLE
doc fails when using a pointer with links

### ISSUE THREAD

**Issue by Sherlock92** [interagent/prmd#230]
I think this is a bug, but maybe it's my misuse of the library.

I have the following schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "title": "test-schema",
  "description": "Test schema demonstrating prmd issue",
  "links": [
    {
      "description": "Info for test-schema.",
      "href": "/whatever",
      "method": "GET",
      "rel": "self",
      "title": "Info"
    }
  ],
  "properties": {
    "$ref": "/schemata/user-profile/properties"
  },
  "type": ["object"],
  "id": "/schemata/test-schema"
}
```

This is failing when I run the `doc` command. 

However, if I remove the `links` property completely, it works fine.  Further, if I remove the `properties.$ref` pointer and keep the `links` property, it works fine too.

For some reason when using *both* links and a pointer in this manner causes it to fail.

I will begin looking into the source but if someone with more familiarity with the library (and ruby for that matter!) could offer some insight that would be great,

Thanks

**Comment by Sherlock92** [comment]
Here is the call stack:

```
/Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/schema.rb:131:in `schema_value_example': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/schema.rb:146:in `block in schema_example'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/schema.rb:144:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/schema.rb:144:in `schema_example'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/schema.rb:158:in `schemata_example'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schemata/link.md.erb:78:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/template.rb:64:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schemata.md.erb:35:in `block in result'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schemata.md.erb:33:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schemata.md.erb:33:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:7:in `block in result'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:4:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:4:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/templates/schema.erb:4:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/core/renderer.rb:49:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/commands/render.rb:34:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/cli/doc.rb:65:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/cli/base.rb:141:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/cli.rb:93:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/bin/prmd:6:in `<top (required)>'
	from /usr/bin/prmd:23:in `load'
	from /usr/bin/prmd:23:in `<main>'
```

**Comment by geemus** [comment]
It looks like the problem is that the property provided is a ref to something that doesn't exist. When trying to document that it tries to build an example of that property, but fails when it is unable to dereference the pointer. Hope that clarifies, but let me know if you have further questions.

**Comment by Sherlock92** [comment]
@geemus the pointer is referenced successfully when there are no `links`, why does adding `links` break the pointer ?

**Comment by geemus** [comment]
It's a matter of how the doc generation works. When there are no links, it doesn't need to try and dereference the links, because it wouldn't appear in the output anywhere. Adding the link makes it necessary to build the example, which then tries to dereference these, resulting in the error. Does that make sense?

**Comment by Sherlock92** [comment]
@geemus maybe i'm missing something, but I still believe there is some underlying bug here that is causing this problem. Here are the exact steps to reproduce the issue, please give it a try.

Schema *test-schema.json*
```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "title": "test-schema",
  "description": "Test schema demonstrating prmd issue",
  "properties": {
    "$ref": "/schemata/another-schema/properties"
  },
  "type": ["object"],
  "id": "/schemata/test-schema"
}
```

Schema *another-schema.json*
```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "title": "another-schema",
  "description": "Another schema demonstrating prmd issue",
  "properties": {
    "one": {
      "type": ["string"],
      "description": "Hello World",
      "example": "Hello World"
    }
  },
  "type": ["object"],
  "id": "/schemata/another-schema"
}
```

I then run the commands:

`prmd combine --meta meta.json ./schemas/ > docs.json`
`prmd doc docs.json > docs.md`

At this point all is well, **the properties for each schema are rendered as expected**, and everyone is super happy. However, if you add following links to the `test-schema` file:

```json
"links": [
  {
    "description": "Info for test-schema.",
    "href": "/whatever",
    "method": "GET",
    "rel": "self",
    "title": "Info"
  }
],
```

Then when running the commands once again, the following error is seen: 

`/Library/Ruby/Gems/2.0.0/gems/prmd-0.7.4/lib/prmd/schema.rb:131:in `schema_value_example': undefined method `[]' for nil:NilClass (NoMethodError`

Thanks

**Comment by geemus** [comment]
We just did some other (unrelated) link related fixing, and retrying this it appears to be solved. Please let me know if you don't find this to be the case. Hopefully I can get a release out with this and other fixes later today.
