### ISSUE TITLE
allow array input types

### ISSUE THREAD

**Issue by reesew** [interagent/prmd#239]
This is similar to #126, but for link's `schema`. If a resource link accepts an array rather than an object, attempting to document this fails `#/definitions/resourceLink/properties/schema`

**Comment by steinnes** [comment]
I think I am having this exact issue, here's my link schema:
```
 "links": [
    {
      "description": "Set conditions",
      "href": "/things/{(%2Fschemata%2Fthing%23%2Fdefinitions%2Fidentity)}/subthing/{(%2Fschemata%2Fsubthing%23%2Fdefinitions%2Fidentity)}/conditions",
      "method": "POST",
      "rel": "create",
      "schema": {"type": "array", "items": {"$ref": "/schemata/condition"}},
      "title": "Update"
    }
  ],
```

here's my error:
```
#/definitions/condition/links/0/schema: failed schema #/definitions/resourceLink/properties/schema: No subschema in "anyOf" matched.
```

I have tried various combinations of this (making a definition out of the list and referencing that directly) but I couldn't have an array as the top-level schema object.  I guessed that may be discouraged by some RESTful principles, but since this is an issue here I figured I'd pitch in.

**Comment by geemus** [comment]
Could you try with master? I think #242 may have fixed this. Thanks!

**Comment by steinnes** [comment]
I'm getting the same error still:

```
$ ~/w/z/prmd/bin/prmd combine --meta schema/meta.json schema/schemata/ | ~/w/z/prmd/bin/prmd verify > schema/schema.json
#/definitions/condition/links/0/schema: failed schema #/definitions/resourceLink/properties/schema: No subschema in "anyOf" matched.
```

The tip of my prmd branch is at `c0fbcaad6eba90bb5d1a486f74217fbec4de02af`.

I'm a total ruby noob but definitely willing to help debug if I can :-)

**Comment by geemus** [comment]
@steinnes no, running it that way should definitely use the latest stuff. Could you share the meta/schemata you are running into issues with? Hopefully I can help pin it down from there. Thanks!

**Comment by geemus** [comment]
@steinnes I just fixed something on master (allowing $ref inside of link), which may also be relevant, so you may want to update and double check there.

**Comment by steinnes** [comment]
Sure, I would prefer not to post the schemas here publicly as it is an internal API under development, but I can create a gist and send it to geemus@gmail.com if that is ok?

Wish this was a more public API I could share openly :-)

**Comment by geemus** [comment]
Sure, no problem, definitely understand. Thanks for sharing it, I'll try to follow up soon.

**Comment by mlr** [comment]
@steinnes I think you might be having the same issue I was, which is that http://interagent.github.io/interagent-hyper-schema isn't reflecting the changes that @geemus made in the commit he mentioned on master.

Could definitely use a +1 on the PR :)

**Comment by reesew** [comment]
I'm not sure how to run prmd from master either. I tried cloning it and then running `./prmd/bin/prmd verify ./schema.json`, but am getting 
```
/schemas/prmd/lib/prmd/link.rb:45:in `<class:Link>': uninitialized constant Prmd::Link::OpenStruct (NameError)
        from /schemas/prmd/lib/prmd/link.rb:2:in `<module:Prmd>'
        from /schemas/prmd/lib/prmd/link.rb:1:in `<top (required)>'
        from /schemas/prmd/lib/prmd.rb:5:in `require_relative'
        from /schemas/prmd/lib/prmd.rb:5:in `<top (required)>'
        from prmd/bin/prmd:3:in `require_relative'
        from prmd/bin/prmd:3:in `<main>'
```
I was also unable to figure out how to install the gem from the source

**Comment by reesew** [comment]
Here is the smallest example I could think of
`schema.json`
```javascript
{
  "$schema": "http://interagent.github.io/interagent-hyper-schema",
  "type": [
    "object"
  ],
  "definitions": {
    "widget": {
      "$schema": "http://json-schema.org/draft-04/hyper-schema",
      "title": "API - Widget",
      "description": "widgets",
      "stability": "prototype",
      "strictProperties": true,
      "type": [
        "object"
      ],
      "definitions": {
        "id": {
          "description": "unique identifier of widget",
          "readOnly": true,
          "format": "uuid",
          "type": [
            "string"
          ]
        },
        "identity": {
          "anyOf": [
            {
              "$ref": "#/definitions/widget/definitions/id"
            }
          ]
        }
      },
      "links": [
        {
          "description": "Update an existing widget.",
          "href": "/widgets/{(%23%2Fdefinitions%2Fwidget%2Fdefinitions%2Fidentity)}",
          "title": "Update",
          "method": "PUT",
          "rel": "update",
          "schema": {
            "type": [
              "array"
            ],
            "items": {
              "$ref": "#/definitions/widget"
            }
          }
        }
      ],
      "properties": {
        "id": {
          "$ref": "#/definitions/widget/definitions/id"
        }
      }
    }
  },
  "properties": {
    "widget": {
      "$ref": "#/definitions/widget"
    }
  },
  "description": "stuff",
  "id": "hello-prmd",
  "links": [
    {
      "href": "https://example.com",
      "rel": "self"
    }
  ],
  "title": "API title"
}
```
`prmd verify schema.json`
`schema.json: #/definitions/widget/links/0/schema: failed schema #/definitions/resourceLink/properties/schema: No subschema in "anyOf" matched.`

It fails the schema check because 
```
                "schema": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/ref"
                        },
                        {
                            "required": ["properties"]
                        },
                        {
                            "required": ["patternProperties"]
                        }
                    ],
                    "required": ["type"]
                }
```
does not allow the `items` property. I hope this helps

**Comment by geemus** [comment]
@reesew I'll try to experiment with your schema shortly. OpenStruct is a stdlib thing, and is included by default in newer ruby, but must be required in older ruby versions. If you add just a `require "openstruct"` to bin/prmd it would probably work (or if you update ruby). I'll add the require on master though also, as this has come up once before and is an easy fix.

**Comment by geemus** [comment]
Oops, actually it should be `require "ostruct"`, also here is a commit adding the require: https://github.com/interagent/prmd/commit/1a7af5476e33e86a4a95667ae58abe3600048da9

**Comment by reesew** [comment]
the message with #246 says it didn't fix doc generation, but now, as far as I can tell, it does

**Comment by geemus** [comment]
@reesew great, thanks for the update. Had meant to get back to this, but just hadn't quite made it yet.
