### ISSUE TITLE
doc generation fails with invalid byte sequence

### ISSUE THREAD

**Issue by rutaihwa** [interagent/prmd#252]
The schema verifies but the doc command fails with `converter.rb:132:in `scan': invalid byte sequence in US-ASCII (ArgumentError)`

The reffered line in converter.rb is `input.scan(regexp) do |indicator, code, tailch,rspace|` my terminal uses `utf-8` and Im puzzled of the error..

The generated doc contains a line `Error in resource: client`

**Comment by geemus** [comment]
Could you provide a sample schema that exhibits this behavior so that I can try to reproduce? Thanks!

**Comment by rutaihwa** [comment]
I guess the issue was with my `ruby env` not with `prmd` now I think it work.

**Comment by geemus** [comment]
Thanks for the update.
