### ISSUE TITLE
Schema does not support URLs with path segments less than two characters

### ISSUE THREAD

**Issue by soulim** [interagent/prmd#261]
There's might be an issue with [`href` pattern][1] because it does not support URL like `/c`. According to the pattern path segment must be at least two characters long.

You could see example here http://rubular.com/r/4qDuw03ec4.

If the pattern is changed to `^(\/([a-z0-9_\-]*[a-z0-9]|\{\(.*\)\}))+$`, then it works for one-character segments as well.

Would you accept a pull request with update for the pattern? 

[1]: https://github.com/interagent/prmd/blob/fa0a688ffce009777b06f0950ca79cab581569ce/schemas/interagent-hyper-schema.json#L110

**Comment by geemus** [comment]
I would be up for allowing single character segments, but I think that version of the regex loses some of the context from the original one. In particular, I think a segment should not start or end with `_` or `-` (which I think is why the original is setup the way it is). Does that make sense? Seems like in that case we might need a more complex regex that has an OR in it between 1-2 alpha-numeric characters and 3+ characters for which the first and last are alpha-numeric. What do you think?

**Comment by soulim** [comment]
I'm glad you like the idea of single character segments, because this exactly the case I have right now on my hands :smile: 

You are right about `-` and `_`. I didn't think carefully enough on suggested regular expression. It must be a bit more complex. Thanks a lot for quick feedback!

**Comment by geemus** [comment]
Happy to help, glad that makes sense. I just wish it didn't mean a painful regex, but I'm not sure we have a good way around it.

**Comment by soulim** [comment]
What do you think about following regex? It uses different approach you've suggested.

```
^(\/((?!-|_)[a-z0-9-_]+(?<!-|_)|\{\(.*\)\}))+$
```

If I didn't miss anything, it should match any segment which consist of alfa-numeric, `-`, and `_`, but not start or end with `-` or `_`. You could see how it works here http://rubular.com/r/79tMHuFu8S. I've tried to test it against many possible options.

**Comment by geemus** [comment]
Sorry for the delay, yeah that looks good to me. Thanks for the rubular link (and thorough set of test cases). It is a regex, which means it is hard for me to wrap my head around without supreme effort, but it does seem to be what we want. Thanks!

**Comment by soulim** [comment]
Thank you for getting back to me! I'm not a regex master myself, so could totally understand you :wink: 

Actually I decided to use this issue as a source of inspiration and try to come up with a solution which expresses requirements you've mentioned and still keep the regex not so complicated. It took me some time to refresh regex knowledge, but it was interesting :smile: 

This particular solution uses [negative lookahead and lookbehind][1]. It helps to express requirements in a nice and shot way.

I'm glad you like the result. So I'm going to open a pull request as soon as possible.

Thank you a lot for feedback and support!

[1]: http://ruby-doc.org/core-2.1.0/Regexp.html#class-Regexp-label-Anchors
