### ISSUE TITLE
Bug related to #223 issue in 0.8 version

### ISSUE THREAD

**Issue by panSarin** [interagent/prmd#266]
I think i hit same error here that was in https://github.com/interagent/prmd/issues/223 

https://gist.github.com/panSarin/f08233cf6b90f91bb937

i already have few similar files for diffrent resources and they work properly. This one always gives me 
```schema/schema.json: #/definitions/outreach_program/properties/outreach_programs: failed schema #/definitions/resource/properties/properties/patternProperties/^[a-z][a-z_]*[a-z]$: No subschema in "anyOf" matched.```

i tried with $ref, and just with type: "string". Both gives me that error. Any ideas? 
@geemus ?

**Comment by geemus** [comment]
I've just released 0.9.0, which seems to work against the schema you have listed there. Could you verify? Thanks!

**Comment by panSarin** [comment]
Yup, it seems to work.

**Comment by geemus** [comment]
Great, thanks for the update.
