### ISSUE TITLE
Add Stability to built docs

### ISSUE THREAD

**Issue by BCVisin** [interagent/prmd#270]
It looks like Heroku has "Stability: production" in their API Docs (https://devcenter.heroku.com/articles/platform-api-reference) but I am not able to get the stability to show up in the prmd generated markdown files. Am I doing something wrong or is this not implemented in prmd?

Thanks,
Blake

**Comment by geemus** [comment]
Hey, great question. We use custom templates for the Heroku docs which add stability, but I don't really see any reason why we couldn't add it here (and just omit it by default if the value is left nil). What do you think? Would you be up for a patch to add it in? Thanks!

**Comment by BCVisin** [comment]
Okay.  Haven't written anything in Ruby before, but that update to the template seems to work for me.  Let me know if that looks good.

Thanks,
Blake
