### ISSUE TITLE
How to express the array of objects ?

### ISSUE THREAD

**Issue by yongwoondwango** [interagent/prmd#281]
If I want to make as blow, how can I write hyper json-schema?
also, want to generate doc base on schema

* json schema 
```
    "object A":{
      "type": ["object"],
      "properties": {
        "type": {
          "$ref": "#/definitions/type"
        },
        "user": {
          "$ref": "#/definitions/user"
        },
      }
    },
    "objectB":{
      "type": ["object"],
      "properties": {
        "type": {
          "$ref": "#/definitions/type"
        },
        "friends": {
          "$ref": "#/definitions/friends"
        },
      }
    },
-----
      "targetSchema":{
        "type": "object",
        "properties": {
          "result" : {
            "type": "array",
            "items":
            {
              "$ref": "/schemata/user#/definitions/objectA",
              "$ref": "/schemata/friends#/definitions/objectB"
            }
          },
          "error" : {
            "$ref": "#/definitions/error"
          }
        }
      }
```
* RESPONSE
```
{
  "result": [
      {object A},
      {obcjet B},
  ],
  "error": {
    "errorCode": 400,
    "errorMessage": "not exist"
  }
}
```

**Comment by geemus** [comment]
You'll want to use the `items` keyword. I see you closed this though, did you have further questions or concerns?

**Comment by yongwoondwango** [comment]
Well.... about question, I don't have further. Thank you for your apply :)

But, have question not related this question. 
How to use render template? 

I don't know how to use, and result when use renter -template !

**Comment by geemus** [comment]
The easiest is to just copy the existing templates and modify them as needed. Then you can pass the root schema template to the command (and from there it uses relative paths to tie everything together).
