### ISSUE TITLE
Properties for a single, large object, off root

### ISSUE THREAD

**Issue by miketheman** [interagent/prmd#288]
Hello!

I'm getting familiar with json schema, and am currently attempting to describe the "top level" of a data object spec.

I had originally started out writing the entire large object by hand - which has proven to be unwieldy as well as likely to not be maintainable long term, so I came across prmd and am excited to use the project.

It appears that the majority of the use cases described are for REST APIs against specific resources, but few show a method for a specification for a versioned document interchange format.

I'm trying to understand how to layout the meta.json vs schemata/*.json to allow for a schema document that has `properties` (and associated definitions?) in the root of the object, and still work with the init/combine/verify/doc flow, and be well-organized - so any help/guidance would be appreciated!

**Comment by geemus** [comment]
Going to close in favor of #289 to hopefully not fragment the conversation.
