### ISSUE TITLE
prmd verify fails on meta.json definitions

### ISSUE THREAD

**Issue by miketheman** [interagent/prmd#289]
Apologies if this is the same/too similar to #288 - I got an example that shows a problem with definitions in meta.json, so I thought it would be best to post the details here.

Given a file meta.json:
```json
{
  "description": "Hello world prmd API",
  "id": "hello-prmd",
  "links": [{
    "href": "https://api.hello.com",
    "rel": "self"
  }],
  "title": "Hello Prmd",
  "definitions": {
    "date": {
      "type": "string",
      "description": "A Date string"
    }
  },
  "properties": {
    "date": {
      "$ref": "#/definitions/date"
    }
  }
}
```

When I run `prmd combine --meta meta.json > schema.json && prmd verify schema.json`
The following message is returned:
```
schema.json: #/definitions/date: failed schema #/properties/definitions/additionalProperties: "definitions", "links", "title" weren't supplied.
```

This appears to be resolved by adding what appear to be artificial additions to the definition in meta.json:
```json
...
  "definitions": {
    "date": {
      "type": "string",
      "description": "A Date string",
      "title": "Date",
      "definitions": {},
      "links": []
    }
  },
...
```

When using schemata, these do not appear to be required for each definition, so is the verifier/doc trying to treat root definitions and properties as resources? Is there a concept of a top-level resource?

**Comment by geemus** [comment]
I think, by and large, top-level stuff in the meta is expected to refer to resources. Though I think that really only applies to properties, rather than definitions. I think the error you are seeing is due to the ref back to the definition from properties.

I'm afraid I am not exactly sure what you mean about "top-level resources" could you give a more concrete example? Just a written explanation/description would be great (rather than a schema, since that has issues as you mention). Thanks!

**Comment by miketheman** [comment]
I think it's taking me some time to wrap my head around this, so my apologies if the verbiage is inaccurate.

In my (to be completed) scenario, I have a a web service that can build or consume a JSON object, validates the object has all the fields required and doesn't have extra that isn't known by both parties (sender and receiver), and then does more things to it (storage, response, etc).
Basically using a JSON schema as a data exchange format that can be shared amongst multiple clients in various languages.
(I _think_ this is what JSON schema, prmd, and all the related tools are meant to support, please tell me if I'm barking up the wrong tree.)

Since a client may POST a blob to an endpoint, say `POST /games` with a JSON object, how does one test a few `games` objects against the prmd-built schema.json file?
So far, all properly-formatted JSON files pass validation, with a command like `validate-schema schema.json samples/sample1.json`, but if I add `"additionalProperties": false` to `meta.json`, validation fails, telling me that I have fields that are valid for `games`.

This is why I think the schema.json compiled from meta.json is using a top-level object - maybe I need to pass some other mechanism to the validation?

**Comment by geemus** [comment]
Ah. I haven't used validate-schema directly. We use https://github.com/interagent/committee for verification (it has some test helpers and allows you to do it on request/response of a rack app) mostly, which has tended to work really well for our purposes.

Unless I still totally misunderstand, your use case doesn't sound particularly unusual or hard to support. You are just using a bit different tooling than us. You may have better luck if you want to use validate-schema to point at the individual schema, rather than the combined one. The combination thing is more of an interagent related tooling specific thing than a broader json-schema pattern.

**Comment by miketheman** [comment]
I've tried the method you recommended of validating the test object against the individual json file in the schemata/ directory.

Example:
```shellsession
$ cat sample_metadata.json
{
  "metadata": {
    "producer": "hands",
    "date": "2016-04-22",
    "author": "miketheman",
    "comments": "This is fine."
  }
}

$ prmd init metadata > schemata/metadata.json # no edits
$ validate-schema schemata/metadata.json sample_metadata.json
schemata/metadata.json#/definitions/identity/anyOf/0: Couldn't resolve URI: /schemata/metadata.
schemata/metadata.json#/definitions/identity/anyOf/1: Couldn't resolve URI: /schemata/metadata.
schemata/metadata.json#/properties/created_at: Couldn't resolve URI: /schemata/metadata.
...
```

So I'm guessing that the `combine` part does the replacements and updates paths of references in a manner that is then usable by `validate-schema`, since it's being done from a filesystem, without a web server in play.

I found validate-schema as part of the json_schema gem, so I'm certain there are other ways to validate a real object against a schema.
I have yet to try out committee - I had trouble finding any open source projects leveraging prmd & committee in their dev cycles for examples of how this might work. Any help/pointers here would be appreciated.

**Comment by geemus** [comment]
https://github.com/interagent/pliny uses it, albeit a bit indirectly (if you use pliny to generate an app, the generated app uses committee). So if you look at that it can hopefully help a bit, ie if you generate an app and a couple resources you should be able to get a sense of how some of those pieces fit together. Sorry I don't have a more direct reference/doc, we should definitely work on that.

**Comment by miketheman** [comment]
I think something that I might have missed, and re-reading https://brandur.org/elegant-apis#meta-schemas I now realize that the `validate-schema` tool is just that - it validates schemas against (presumably) hyper-schemas, not necessarily objects-to-schemas.

I'll close this one for now, and continue to try using pliny to mock up a couple of resources and see how I might go about validating them - thanks!

**Comment by geemus** [comment]
@miketheman thanks for the update, sounds like a plan. Just let me know if you still end up with questions or need any further clarifications.

**Comment by miketheman** [comment]
@geemus i think I'm coming to more understanding about how things might be structured.

It appears "what I want" is to define a few models with relationships (example: game has many players, game has one-or-more periods, players have stats) but create an endpoint that receives a single payload encompasses an entire game Object, which can then split the pieces apart and store them appropriately.

I'm not certain how to structure that concept in pliny, so any ideas would help.

**Comment by geemus** [comment]
Good question, I haven't really done anything quite like that myself, so I'm not very sure. $ref should help somewhat to at least avoid duplication. One way might be to kind of structure this as a BFF (backend-for-frontend) kind of thing. ie have an endpoint that receives this and effectively fans out to the individual/simpler things. This has it's own issues/complexities though (usually that pattern is better/easier in the lookup case than the create case). Perhaps the better question would be, is it really necessary in terms of the design that all this data be passed in a single call, vs being broken out into more granular bits? (the answer may well be yes, if for instance transactionality of the whole thing is important).
