### ISSUE TITLE
Namespaces?

### ISSUE THREAD

**Issue by michaelsauter** [interagent/prmd#299]
I'm trying to use a namespace, and I'm not sure this is currently supported. Let me explain:

Say I'm having a resource "user", defined in `schemata/user.yml`. There is one endpoint, `GET /users/:id`. Now I want to implement a search for users. One choice would be to model this as a filter of "list", so `GET /users?some=value`. That would be easy to model in JSON schema.

However, I'd like to model the search as a resource, under the user namespace, so `POST /users/searches`. That way, I can use POST, it's separated from listing users and I can easily turn this into a saved search by persisting the search parameters. Now my question is how to model this. I don't want a top-level "search" resource since I might have searches for different resources. I tried creating `schemata/user/search.yml` but couldn't get it to work. The error reported was `Couldn't resolve pointer "#/definitions/user/search/definitions/id".` Also tried `schemata/users/search.yml` with the same result.

Is something like this possible to do within the current schema? It feels like I'm missing something obvious. If it is supported in some way, maybe we could add an example to showcase this?

**Comment by yukitoto** [comment]
I'm also face with this issue..

**Comment by geemus** [comment]
I guess my inclination would be to have it distinct, but perhaps just name as something like `schemata/user-search` or similar. Would that be workable for you?

**Comment by michaelsauter** [comment]
@geemus Sure, that would be an option. I just assumed there would be a way to have some folder structure ... Using `user-search` is possible but obviously not ideal.

**Comment by geemus** [comment]
@michaelsauter that's fair, and maybe it is about time for us to come up with patterns to allow this kind of nesting. It just hadn't really come up this concretely or been deeply discussed previously. Happy to discuss further if you want to help move us in that direction. Thanks!
