### ISSUE TITLE
can/should we provide for asserting about headers?

### ISSUE THREAD

**Issue by geemus** [interagent/prmd#3]

**Comment by BCVisin** [comment]
So how does Heroku generate docs with Response Examples that have more than 

`HTTP/1.1 200 OK`

https://devcenter.heroku.com/articles/platform-api-reference
Response Examples
````
HTTP/1.1 200 OK
ETag: "0123456789abcdef0123456789abcdef"
Last-Modified: Sun, 01 Jan 2012 12:00:00 GMT
RateLimit-Remaining: 2400
```

Is this custom/outside of prmd?

**Comment by geemus** [comment]
Yeah, we override the default templates with ones that include a few additional/expected headers. I'd love to extend the default headers far enough to not need to do that, but we haven't managed to just yet.
