### ISSUE TITLE
How to use my own hyper schema instead of interagent-hyper-schema?

### ISSUE THREAD

**Issue by goto100** [interagent/prmd#300]
interagent-hyper-schema is too strict in href's pattern, I want to use my own schema, but `prmd combine` command don't have a option to change the default "$schema" value.

**Comment by geemus** [comment]
I would be open to supporting that as an option, would you be interested in helping with a pull request? Thanks!

**Comment by goto100** [comment]
I think it's not necessary, why would I need verify the *combined* json? I think the following commands is better than recommended one:

```
prmd verify schemata/*.json | prmd combine --meta meta.json schemata/ | prmd doc --prepend docs/overview.md > api.md
```

is better than:

```
prmd combine --meta meta.json schemata/ | prmd verify | prmd doc --prepend docs/overview.md > api.md
```

every schema could have it own $schema, and the combined json don't need any schema, because it no need to verify.

but `prmd verify` gives me "Couldn't resolve URI" error. Maybe a custom loader could resolve this.

**Comment by goto100** [comment]
prmd **really** too strict for "href" schema, all of my problem because of this. Is there a workaround to avoid this?

**Comment by geemus** [comment]
I'm not sure that a combined schema still works well or entirely makes sense of the sub-schemas do not have a shared basis in a particular schema. Additionally, verify has assumptions about things being in the combined format in particular to help ensure that everything was brought together as expected. I gather your concern boils down more specifically to query strings not being as well supported as you would like for post. So I think I'm going to close this particular issue in favor of the more constrained discussion and solution put forth in #253. Do let me know if that is over simplifying or fails to address other concerns. Thanks!
