### ISSUE TITLE
what's the meaning of the name "prmd"?

### ISSUE THREAD

**Issue by goto100** [interagent/prmd#308]
I'm writing a mock tool with prmd schema standard, I want to name it with a similar name like `prmd-mock`, but I don't know the extacly meaning of `prmd`, can you explain it?

**Comment by geemus** [comment]
It's short for "pyramid" and was kind of an inside joke. Basically it felt like we were trying to use schema for everything (validation, client-generation, documentation, etc) and I joked that it felt like a pyramid scheme (ie too good to be true). The name just kind of stuck.

I'm not sure what you want to do with the mocks exactly, but you may want to check out the committee stub middleware, as it might already do some of what you want: https://github.com/interagent/committee#committeemiddlewarestub

**Comment by goto100** [comment]
1. I'm not using ruby;
2. committee-stub don't generate data, just get data from `example`;

I'm writing a Node.js mock tools to generate mock data with [json-schema-faker](https://github.com/json-schema-faker/json-schema-faker) and [ajv](https://github.com/epoberezkin/ajv).

**Comment by geemus** [comment]
Got it, thanks for the clarification.

**Comment by goto100** [comment]
Do you have any recommendation of naming my mock tool? I think `prmd-mock` is not very suitable :)

**Comment by geemus** [comment]
@goto100 that sounds good to me, go for it!

**Comment by goto100** [comment]
Thanks~

**Comment by goto100** [comment]
@geemus I've released my mock tool, welcome to have a try~

https://github.com/goto100/prmd-mock

**Comment by geemus** [comment]
Congrats and thanks for the heads up!
