### ISSUE TITLE
Problem creating TOC with Rake task

### ISSUE THREAD

**Issue by habitullence** [interagent/prmd#319]
I've updated to 0.13 but having trouble getting TOC to work with the Rake task example. Rake task updated to:

```
namespace :schema do
  Prmd::RakeTasks::Combine.new do |t|
    t.options[:meta] = "docs/schema/meta.json"
    t.paths << "docs/schema/schemata"
    t.output_file = "docs/schema/schema.json"
  end

  Prmd::RakeTasks::Verify.new do |t|
    t.files << "docs/schema/schema.json"
  end

  Prmd::RakeTasks::Doc.new do |t|
    t.options[:settings] = "docs/settings.json"
    t.files = { "docs/schema/schema.json" => "docs/schema/schema.md" }
  end
end
```

`docs/settings.json` looks like:

```
{
  "doc": {
    "toc": true
  }
}
```

Doesn't produce TOC, any ideas?

**Comment by niaeashes** [comment]
I have same trouble. Try this.
```
namespace :schema do
  Prmd::RakeTasks::Doc.new do |t|
    t.options[:doc] = { toc: true }
    t.options[:prepend] = ['api/overview.md']
    t.files = { 'dist/schema.json' => 'md/schema.md' }
  end
end
```

**Comment by habitullence** [comment]
Hi @niaeashes, thanks. Gave it a go but didn't work for me.

**Comment by geemus** [comment]
@habitullence I think it should work (especially the @niaeashes version, even if the file settings didn't). Could you share the schema you are trying this with? Could be an issue there, rather than in the command itself. Thanks!

**Comment by geemus** [comment]
Looks like #320 should fix this.

**Comment by habitullence** [comment]
Can confirm #320 fixes, thanks :)
