### ISSUE TITLE
Documentation: identity vs id property

### ISSUE THREAD

**Issue by HolgerPeters** [interagent/prmd#326]
https://github.com/interagent/prmd/blob/master/docs/schemata.md#definitions states that the definition section must contain the definition of an `identity` property. The following example then defines an `id` property. This seems like an inconsistency in the document.

**Comment by geemus** [comment]
Good catch, should now be here: https://github.com/interagent/prmd/commit/56ee715f2301fff0edebfcd2a353d1e7fddf1964
